### ISSUE TITLE
AEdwards92: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by AEdwards92** [ismailoglu/RT-analyzer#3]
<p><br><blockquote>This issue was created by @AEdwards92 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by slacktracer** [comment]
Perhaps we should close this one for now, @ismailoglu 
=)

**Comment by ismailoglu** [comment]
Agreed.
@AEdwards92, if you are still reading this feel free to email us. Even if you don't have time for this project we can include you in future projects.
