### ISSUE TITLE
Calculation stops if some sample-probe pairs are missing

### ISSUE THREAD

**Issue by ismailoglu** [ismailoglu/RT-analyzer#5]
The app assumes every sample in the sample list will have values for every probe in the probe list. This is not always the case in real applications. Currently the app doesn't return values for Step 2 if some values are missing.

The app should just ignore the missing sample-probe pairs and do the calculations for everything else.

**Comment by slacktracer** [comment]
Started to work on it on: 655badc623f8abe7b3a87e96f0abbd66fab34b4b

Will make a few more tests before closing this issue. Take a look whenever you can, @ismailoglu =)

**Comment by ismailoglu** [comment]
This seems to be working now. Do you think the issue can be closed?

**Comment by slacktracer** [comment]
@ismailoglu 

Yeah. =)
