### ISSUE TITLE
Irfan Ali: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by irfanalidv** [ismailoglu/RT-analyzer#9]
Visualization and Data Analysis interest me to get into Project.
I'm pursuing B.Tech at Alliance University specialize in Computer Science and Engineering minors in Data Science ,Big Data ,Machine Learning.<p><br><blockquote>This issue was created by @irfanalidv via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by ismailoglu** [comment]
Hi @irfanalidv, great to hear from you. Thanks for volunteering.

We are actually thinking about how to visualize our data currently. @slacktracer wrote the part that crunches the raw data, now we need to convert it to graphs.

What do you think @slacktracer?

Best
Ismail

**Comment by slacktracer** [comment]
Hi @irfanalidv,

We are getting into data visualization at this moment. You certainly can have a lot to add to our project. =)

Please, do familiarize yourself with it. Did you have to time to read the whole README.md? Then check the amazing video directed, acted and narrated by @ismailoglu explaining how our current alpha demo works. (https://www.youtube.com/watch?v=_YxGhbOOT4w)
=)

You'll see what kind of data we're extracting.

Right now we're going for pretty standard smart charts (mostly showing all data as columns and offering as many filter options as possible). Perhaps you'll have suggestions on better visualization, some software or tech we can use or anything else.

Let us know how it goes for you and ask us anything you want to know.


The kind of charts we're working on:
http://anzol.biz/chart/2/
http://anzol.biz/chart/3/

Our online demo:
http://anzol.biz/rt-analyzer-alpha-1.0/


Tell us how you would like to collaborate. What skills are you interested in sharing with us. =)
Let's talk.
